### ISSUE TITLE
Request / Suggestion PLEASE

### ISSUE THREAD

**Issue by ghost** [Khazoda/block-breaker-placer#1]
**The sound is too loud**
_Use the default dispenser/dropper sound or a quiet one_

**Item durability** 
_like vanilla : -1 durability if I use the right tool to break a block, -2 if I use the wrong one_

**Breaking delay**
_Because It's too op, use the vanilla one : better tools = faster breaking_

I play a lot of survival with friends and It will enchance the experience for sur, thx for reading

**Comment by khazoda** [comment]
Thanks for the suggestions!

```The sound is too loud```
I will definitely take a look at the sound balance, I must have missed something in testing, thank you.

```Item durability```
This is something I thought about, but believe would make the breaker too annoying to use. For example, if you've set up a cobblestone generator, you'd have to replace the picks constantly. I think the trade-off of having to craft the breaker and set it up in a location with a contraption should be the challenge, not replacing tools all the time.

```Breaking delay```
In early development I actually tried implementing this, but there's quite a bit that can go wrong with client-server sync etc. 
Although I'm open to opinions on this, I think the current implementation isn't too OP (due to the reasons mentioned in the second point)

Hopefully these answers are sufficient, and feel free to open further issues if you want!

**Comment by khazoda** [comment]
Sound balance fixed in 7999001
